// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoGQ8qdSSFJY62Se6irXBQU4Otx79TqOM',
    appId: '1:682081073024:android:43006bd1ecb4057a3eb365',
    messagingSenderId: '682081073024',
    projectId: 'event-manager-e1ee6',
    storageBucket: 'event-manager-e1ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl_zDETTNfAFS6TngE8cKOAB52oc50cA',
    appId: '1:682081073024:ios:3302d60fd770df343eb365',
    messagingSenderId: '682081073024',
    projectId: 'event-manager-e1ee6',
    storageBucket: 'event-manager-e1ee6.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjl_zDETTNfAFS6TngE8cKOAB52oc50cA',
    appId: '1:682081073024:ios:3302d60fd770df343eb365',
    messagingSenderId: '682081073024',
    projectId: 'event-manager-e1ee6',
    storageBucket: 'event-manager-e1ee6.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFJbOXqtQEDo7OzEOATT7rjdnU5MRc0Q',
    appId: '1:682081073024:web:4827d4713e0a72ba3eb365',
    messagingSenderId: '682081073024',
    projectId: 'event-manager-e1ee6',
    authDomain: 'event-manager-e1ee6.firebaseapp.com',
    storageBucket: 'event-manager-e1ee6.firebasestorage.app',
    measurementId: 'G-1R1SLDHEL6',
  );
}
